### PR TITLE
fix: updater config v2

### PR DESCRIPTION
**Pull request by buenaflor**
#skip-changelog

### CODE REVIEW

**Comment by buenaflor** [comment]
Works on @v1

**Review by bruno-garcia — APPROVED** [review]

**Comment by bruno-garcia** [comment]
@vaind seems like v2 breaks because of a token thing but v1 works. 

But repo has `CI_DEPLOY_KEY` 

Diff is long: https://github.com/getsentry/github-workflows/compare/v1...v2.8.1 (assuming this is what v1 to v2 does)
maybe the value was always wrong but didn't get used in v1?
new version has `      api-token: ${{ secrets.CI_DEPLOY_KEY }}`

**Review by vaind — CHANGES_REQUESTED** [review]
No need to roll back, just fix the config, see my pr #172

**Comment by vaind** [comment]
> @vaind seems like v2 breaks because of a token thing but v1 works.
> 
> failure:
> 
> > The workflow is not valid. .github/workflows/update-deps.yml (Line: 14, Col: 11): Secret api-token is required, but not provided while calling. .github/workflows/update-deps.yml (Line: 20, Col: 18): Invalid secret, api_token is not defined in the referenced workflow.
> 
> Diff is long: [getsentry/github-workflows@v1...v2.8.1](https://github.com/getsentry/github-workflows/compare/v1...v2.8.1) (assuming this is what v1 to v2 does) maybe the value was always wrong but didn't get used in v1? new version has ` api-token: ${{ secrets.CI_DEPLOY_KEY }}`
> 
> But repo has `CI_DEPLOY_KEY` (possibly is empty if I fucked it up somehow

No need to look at the diff between v1 and the latest v2. The release notes say what changed at as very first item https://github.com/getsentry/github-workflows/releases/tag/v2.0.0
> Rename api_token secret to api-token (https://github.com/getsentry/github-workflows/pull/21)

**Pull request merged**
